### ISSUE TITLE
Getting error while trying to open camera to scan

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#49] opened 2021-05-31 11:03 UTC
1. I am getting an error while clicking on the "start scan" button. It works fine with your code pen example.

![image](https://user-images.githubusercontent.com/67706842/120183582-82e08080-c22d-11eb-9baa-87748a4e08b4.png)

2. I am getting the below error in the code for the WasmType.
![image](https://user-images.githubusercontent.com/67706842/120183783-c89d4900-c22d-11eb-879d-52c6415169c1.png)

Please let me know what I am missing here.

**Comment by vjekoart** [comment] 2021-06-02 09:32
Hi @pjain8889,

For the first problem, could you note which package versions are you using and which version is displayed in the browser console once the SDK is unlocked?

Regarding the second problem, information about the package version will be helpful for us to know how to proceed. Also, could you give us a full value of the `loadSettings.engineLocation` property?

Sincerely,
Vjekoslav

**Comment by pjain8889** [comment] 2021-06-02 16:27
Hi @vjekoart,

1. The version number is displayed in the console during SDK unlocking is 5.11.4. Please see below screenshot.

![image](https://user-images.githubusercontent.com/67706842/120516885-7b67d580-c3ed-11eb-92f5-b1a05834528d.png)

2. The loadSettings.engineLocation is https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.4/resources/.

Let me know if any other information is required.

Thanks,
Prashant

**Comment by vjekoart** [comment] 2021-06-07 09:24
Hi @pjain8889,

Thank you for the information. I'm still unable to reproduce the issue.

Could you provide information about the web browser and OS you're using?

Sincerely,
Vjekoslav

**Comment by pjain8889** [comment] 2021-06-07 09:28
I am using Chrome browser(Version 91.0.4472.77 ) and Windows 10.
I resolved the first issue bit still not able to fix the second issue. Can you please help me out there.

Thanks,
Prashant Jain

**Comment by vjekoart** [comment] 2021-06-07 09:44
Hi @pjain8889,

I'm going to close this issue since the main problem with initiating the camera scan action is resolved.

We should take further communication regarding the issue with `wasmType` to #48.

Sincerely,
Vjekoslav

**Closed by vjekoart** 2021-06-07 09:44 UTC
